### ISSUE TITLE
Links to Data 

### ISSUE THREAD

**Issue by Ofentswe1** [Ofentswe1/FIFA#1]
Lets have links where we can get all the data for players and country teams

**Comment by InathiM** [comment]
I found a link : https://www.kaggle.com/hiteshp/exploring-fifa-2018-dataset/data


[CompleteDataset.csv.zip](https://github.com/Ofentswe1/FIFA/files/2094112/CompleteDataset.csv.zip)
[PlayerAttributeData.csv.zip](https://github.com/Ofentswe1/FIFA/files/2094113/PlayerAttributeData.csv.zip)
[PlayerPersonalData.csv.zip](https://github.com/Ofentswe1/FIFA/files/2094114/PlayerPersonalData.csv.zip)
[PlayerPlayingPositionData.csv.zip](https://github.com/Ofentswe1/FIFA/files/2094115/PlayerPlayingPositionData.csv.zip)
